"""
Sample catalogue, mirrored from server/src/seed/products.data.js so both backends seed
identical data.

`category` / `sub_category` values must stay in sync with the slugs in
src/app/data/category.data.ts — the storefront filters by comparing them lowercased.

The discount spread is intentional: /products/feed/today-deals needs items at 70%+ and
/feed/discounted needs 50%+, so both feeds return something after seeding.
"""

SAMPLE_PRODUCTS = [
    {
        "title": "Galaxy A55 5G Smartphone",
        "price": 32999,
        "stock": 40,
        "brand": "Samsung",
        "color": "Awesome Navy",
        "category": "electronics",
        "sub_category": "mobiles",
        "image": "https://picsum.photos/seed/galaxy-a55/600/600",
        "description": "6.6-inch Super AMOLED display, 50MP OIS camera, 5000mAh battery.",
        "discount": 18,
        "rating": 4.4,
        "sales": 320,
        "views": 5400
    },
    {
        "title": "iPhone 15 128GB",
        "price": 79900,
        "stock": 18,
        "brand": "Apple",
        "color": "Blue",
        "category": "electronics",
        "sub_category": "mobiles",
        "image": "https://picsum.photos/seed/iphone-15/600/600",
        "description": "A16 Bionic, Dynamic Island, 48MP main camera, USB-C.",
        "discount": 8,
        "rating": 4.7,
        "sales": 510,
        "views": 12400
    },
    {
        "title": "ThinkPad E14 Gen 5 Laptop",
        "price": 68990,
        "stock": 12,
        "brand": "Lenovo",
        "color": "Graphite Black",
        "category": "electronics",
        "sub_category": "laptops",
        "image": "https://picsum.photos/seed/thinkpad-e14/600/600",
        "description": "Ryzen 7 7730U, 16GB RAM, 512GB SSD, 14-inch WUXGA.",
        "discount": 22,
        "rating": 4.3,
        "sales": 140,
        "views": 3100
    },
    {
        "title": "MacBook Air 13 M3",
        "price": 114900,
        "stock": 9,
        "brand": "Apple",
        "color": "Midnight",
        "category": "electronics",
        "sub_category": "laptops",
        "image": "https://picsum.photos/seed/macbook-air-m3/600/600",
        "description": "8-core CPU, 16GB unified memory, 18-hour battery life.",
        "discount": 6,
        "rating": 4.8,
        "sales": 260,
        "views": 9800
    },
    {
        "title": "WH-1000XM5 Noise Cancelling Headphones",
        "price": 29990,
        "stock": 55,
        "brand": "Sony",
        "color": "Black",
        "category": "electronics",
        "sub_category": "headphones",
        "image": "https://picsum.photos/seed/wh1000xm5/600/600",
        "description": "Industry-leading ANC, 30-hour battery, multipoint pairing.",
        "discount": 35,
        "rating": 4.6,
        "sales": 430,
        "views": 8700
    },
    {
        "title": "Wireless Earbuds Pro",
        "price": 4999,
        "stock": 200,
        "brand": "boAt",
        "color": "White",
        "category": "electronics",
        "sub_category": "headphones",
        "image": "https://picsum.photos/seed/earbuds-pro/600/600",
        "description": "45-hour playback, ENx noise cancellation, low-latency gaming mode.",
        "discount": 72,
        "rating": 4.1,
        "sales": 1500,
        "views": 22000
    },
    {
        "title": "Galaxy Watch 6 Classic",
        "price": 43999,
        "stock": 25,
        "brand": "Samsung",
        "color": "Silver",
        "category": "electronics",
        "sub_category": "smart-watches",
        "image": "https://picsum.photos/seed/watch6-classic/600/600",
        "description": "Rotating bezel, BioActive sensor, sleep coaching.",
        "discount": 28,
        "rating": 4.4,
        "sales": 180,
        "views": 4600
    },
    {
        "title": "Fitness Tracker Band 8",
        "price": 3499,
        "stock": 300,
        "brand": "Xiaomi",
        "color": "Graphite",
        "category": "electronics",
        "sub_category": "smart-watches",
        "image": "https://picsum.photos/seed/band-8/600/600",
        "description": "1.62-inch AMOLED, 16-day battery, 150+ sport modes.",
        "discount": 75,
        "rating": 4.2,
        "sales": 2100,
        "views": 31000
    },
    {
        "title": "Men's Regular Fit Oxford Shirt",
        "price": 2499,
        "stock": 120,
        "brand": "Arrow",
        "color": "Sky Blue",
        "category": "fashion",
        "sub_category": "mens-fashion",
        "image": "https://picsum.photos/seed/oxford-shirt/600/600",
        "description": "100% cotton, wrinkle-resistant, button-down collar.",
        "discount": 55,
        "rating": 4,
        "sales": 640,
        "views": 7300
    },
    {
        "title": "Women's Anarkali Kurta Set",
        "price": 3299,
        "stock": 80,
        "brand": "Libas",
        "color": "Maroon",
        "category": "fashion",
        "sub_category": "womens-fashion",
        "image": "https://picsum.photos/seed/anarkali-set/600/600",
        "description": "Printed viscose rayon kurta with dupatta and palazzo.",
        "discount": 62,
        "rating": 4.3,
        "sales": 890,
        "views": 11200
    },
    {
        "title": "30L Casual Laptop Backpack",
        "price": 1999,
        "stock": 150,
        "brand": "Wildcraft",
        "color": "Charcoal",
        "category": "bags",
        "sub_category": "backpacks",
        "image": "https://picsum.photos/seed/backpack-30l/600/600",
        "description": "Padded 15.6-inch laptop sleeve, water-resistant polyester.",
        "discount": 48,
        "rating": 4.2,
        "sales": 720,
        "views": 9100
    },
    {
        "title": "55L Rucksack Travel Backpack",
        "price": 4599,
        "stock": 45,
        "brand": "Quechua",
        "color": "Forest Green",
        "category": "bags",
        "sub_category": "rucksack-travel-backpack",
        "image": "https://picsum.photos/seed/rucksack-55l/600/600",
        "description": "Adjustable back system, rain cover, top and side access.",
        "discount": 30,
        "rating": 4.5,
        "sales": 210,
        "views": 3800
    },
    {
        "title": "Cabin Trolley Travel Bag",
        "price": 5499,
        "stock": 60,
        "brand": "American Tourister",
        "color": "Red",
        "category": "bags",
        "sub_category": "travel-bags",
        "image": "https://picsum.photos/seed/cabin-trolley/600/600",
        "description": "55cm hard-shell cabin luggage with TSA lock and spinner wheels.",
        "discount": 42,
        "rating": 4.4,
        "sales": 380,
        "views": 6200
    },
    {
        "title": "Air Cushion Running Sneakers",
        "price": 5999,
        "stock": 90,
        "brand": "Nike",
        "color": "White / Volt",
        "category": "footwear",
        "sub_category": "sneakers",
        "image": "https://picsum.photos/seed/running-sneakers/600/600",
        "description": "Breathable knit upper with responsive foam midsole.",
        "discount": 38,
        "rating": 4.5,
        "sales": 950,
        "views": 15400
    },
    {
        "title": "Everyday Comfort Sandals",
        "price": 1299,
        "stock": 180,
        "brand": "Bata",
        "color": "Tan",
        "category": "footwear",
        "sub_category": "sandals",
        "image": "https://picsum.photos/seed/comfort-sandals/600/600",
        "description": "Cushioned footbed, adjustable straps, anti-skid sole.",
        "discount": 71,
        "rating": 3.9,
        "sales": 1240,
        "views": 13800
    },
    {
        "title": "Premium Basmati Rice 5kg",
        "price": 899,
        "stock": 400,
        "brand": "India Gate",
        "color": "N/A",
        "category": "groceries",
        "sub_category": "rice",
        "image": "https://picsum.photos/seed/basmati-rice/600/600",
        "description": "Aged two years for extra-long grains and low stickiness.",
        "discount": 20,
        "rating": 4.6,
        "sales": 3200,
        "views": 18900
    },
    {
        "title": "Cold Pressed Mustard Oil 1L",
        "price": 349,
        "stock": 500,
        "brand": "Fortune",
        "color": "N/A",
        "category": "groceries",
        "sub_category": "oil",
        "image": "https://picsum.photos/seed/mustard-oil/600/600",
        "description": "Kachi ghani, single-filtered, rich in omega-3.",
        "discount": 15,
        "rating": 4.3,
        "sales": 2800,
        "views": 12100
    },
    {
        "title": "Assorted Namkeen Snack Box",
        "price": 599,
        "stock": 260,
        "brand": "Haldiram",
        "color": "N/A",
        "category": "groceries",
        "sub_category": "snacks",
        "image": "https://picsum.photos/seed/namkeen-box/600/600",
        "description": "Six-pack variety of traditional Indian savoury snacks.",
        "discount": 52,
        "rating": 4.4,
        "sales": 1700,
        "views": 14300
    },
    {
        "title": "Matte Liquid Lipstick Set of 5",
        "price": 1499,
        "stock": 140,
        "brand": "Maybelline",
        "color": "Nude Shades",
        "category": "beauty",
        "sub_category": "makeup",
        "image": "https://picsum.photos/seed/lipstick-set/600/600",
        "description": "Transfer-proof, 16-hour wear, non-drying matte formula.",
        "discount": 58,
        "rating": 4.2,
        "sales": 1350,
        "views": 16700
    },
    {
        "title": "Vitamin C Brightening Serum 30ml",
        "price": 1099,
        "stock": 220,
        "brand": "Minimalist",
        "color": "N/A",
        "category": "beauty",
        "sub_category": "skincare",
        "image": "https://picsum.photos/seed/vitamin-c-serum/600/600",
        "description": "10% ethylated vitamin C with acetyl glucosamine.",
        "discount": 25,
        "rating": 4.5,
        "sales": 1900,
        "views": 21000
    },
    {
        "title": "Whey Protein Isolate 1kg",
        "price": 3499,
        "stock": 110,
        "brand": "Optimum Nutrition",
        "color": "Chocolate",
        "category": "wellness",
        "sub_category": "supplements",
        "image": "https://picsum.photos/seed/whey-isolate/600/600",
        "description": "25g protein and 5.5g BCAA per serving, 33 servings.",
        "discount": 24,
        "rating": 4.6,
        "sales": 870,
        "views": 10400
    },
    {
        "title": "Anti-Slip Yoga Mat 6mm",
        "price": 1299,
        "stock": 190,
        "brand": "Boldfit",
        "color": "Purple",
        "category": "wellness",
        "sub_category": "yoga",
        "image": "https://picsum.photos/seed/yoga-mat/600/600",
        "description": "TPE dual-layer mat with alignment lines and carry strap.",
        "discount": 64,
        "rating": 4.1,
        "sales": 1100,
        "views": 12800
    },
    {
        "title": "22K Gold Plated Jhumka Earrings",
        "price": 2299,
        "stock": 70,
        "brand": "Tarinika",
        "color": "Gold",
        "category": "jewellery",
        "sub_category": "gold",
        "image": "https://picsum.photos/seed/gold-jhumka/600/600",
        "description": "Temple-jewellery design with pearl drops, anti-tarnish coating.",
        "discount": 45,
        "rating": 4.3,
        "sales": 420,
        "views": 7900
    },
    {
        "title": "925 Sterling Silver Chain Bracelet",
        "price": 1899,
        "stock": 95,
        "brand": "GIVA",
        "color": "Silver",
        "category": "jewellery",
        "sub_category": "silver",
        "image": "https://picsum.photos/seed/silver-bracelet/600/600",
        "description": "Rhodium-plated, hypoallergenic, adjustable clasp.",
        "discount": 33,
        "rating": 4.4,
        "sales": 560,
        "views": 8300
    },
    {
        "title": "Solitaire Zircon Ring",
        "price": 1599,
        "stock": 130,
        "brand": "GIVA",
        "color": "Rose Gold",
        "category": "jewellery",
        "sub_category": "rings",
        "image": "https://picsum.photos/seed/zircon-ring/600/600",
        "description": "Brilliant-cut American diamond in a six-prong setting.",
        "discount": 70,
        "rating": 4,
        "sales": 780,
        "views": 11500
    },
    {
        "title": "Sheesham Wood 3-Seater Sofa",
        "price": 42999,
        "stock": 8,
        "brand": "Urban Ladder",
        "color": "Walnut",
        "category": "home-living",
        "sub_category": "furniture",
        "image": "https://picsum.photos/seed/sheesham-sofa/600/600",
        "description": "Solid wood frame with high-density foam cushioning.",
        "discount": 27,
        "rating": 4.2,
        "sales": 95,
        "views": 4200
    },
    {
        "title": "Ergonomic Mesh Office Chair",
        "price": 12999,
        "stock": 34,
        "brand": "Green Soul",
        "color": "Black",
        "category": "home-living",
        "sub_category": "office-chair",
        "image": "https://picsum.photos/seed/office-chair/600/600",
        "description": "Adjustable lumbar support, 4D armrests, 135° recline.",
        "discount": 50,
        "rating": 4.5,
        "sales": 640,
        "views": 13100
    },
    {
        "title": "Macrame Wall Hanging Decor",
        "price": 899,
        "stock": 160,
        "brand": "Fabindia",
        "color": "Ivory",
        "category": "home-living",
        "sub_category": "home-decor",
        "image": "https://picsum.photos/seed/macrame-decor/600/600",
        "description": "Handwoven cotton cord on a natural pine dowel.",
        "discount": 40,
        "rating": 4.1,
        "sales": 350,
        "views": 5600
    },
    {
        "title": "Triply Stainless Steel Cookware Set",
        "price": 6499,
        "stock": 48,
        "brand": "Milton",
        "color": "Steel",
        "category": "home-living",
        "sub_category": "kitchenware",
        "image": "https://picsum.photos/seed/cookware-set/600/600",
        "description": "Five-piece induction-friendly set with riveted handles.",
        "discount": 36,
        "rating": 4.4,
        "sales": 480,
        "views": 7100
    },
    {
        "title": "400 TC Cotton Bedsheet with 2 Pillow Covers",
        "price": 1799,
        "stock": 210,
        "brand": "Bombay Dyeing",
        "color": "Teal",
        "category": "home-living",
        "sub_category": "bedding-bath",
        "image": "https://picsum.photos/seed/cotton-bedsheet/600/600",
        "description": "King size, sateen weave, colourfast and pre-shrunk.",
        "discount": 57,
        "rating": 4.3,
        "sales": 1250,
        "views": 15900
    },
    {
        "title": "Gentle Baby Lotion 400ml",
        "price": 449,
        "stock": 320,
        "brand": "Mamaearth",
        "color": "N/A",
        "category": "baby-kids",
        "sub_category": "baby-care",
        "image": "https://picsum.photos/seed/baby-lotion/600/600",
        "description": "Shea butter and jojoba oil, dermatologically tested, no parabens.",
        "discount": 22,
        "rating": 4.5,
        "sales": 1450,
        "views": 13400
    },
    {
        "title": "250-Piece Building Blocks Set",
        "price": 1299,
        "stock": 175,
        "brand": "Funskool",
        "color": "Multicolour",
        "category": "baby-kids",
        "sub_category": "toys-games",
        "image": "https://picsum.photos/seed/building-blocks/600/600",
        "description": "BIS-certified non-toxic ABS blocks with storage box.",
        "discount": 46,
        "rating": 4.4,
        "sales": 990,
        "views": 12200
    },
    {
        "title": "Kids' Cotton T-Shirt Pack of 3",
        "price": 999,
        "stock": 240,
        "brand": "Hopscotch",
        "color": "Assorted",
        "category": "baby-kids",
        "sub_category": "kids-clothing-accessories",
        "image": "https://picsum.photos/seed/kids-tshirts/600/600",
        "description": "Soft combed cotton, tagless neck, ages 2-8.",
        "discount": 68,
        "rating": 4.2,
        "sales": 1320,
        "views": 14100
    },
    {
        "title": "Adult Dry Dog Food 10kg",
        "price": 3299,
        "stock": 85,
        "brand": "Pedigree",
        "color": "N/A",
        "category": "pet-supplies",
        "sub_category": "pet-food",
        "image": "https://picsum.photos/seed/dog-food/600/600",
        "description": "Chicken and vegetables, complete nutrition for adult dogs.",
        "discount": 19,
        "rating": 4.5,
        "sales": 1080,
        "views": 9600
    },
    {
        "title": "Pet Grooming Deshedding Brush",
        "price": 699,
        "stock": 230,
        "brand": "Captain Zack",
        "color": "Blue",
        "category": "pet-supplies",
        "sub_category": "grooming",
        "image": "https://picsum.photos/seed/grooming-brush/600/600",
        "description": "Stainless steel comb with self-cleaning retractable bristles.",
        "discount": 53,
        "rating": 4,
        "sales": 610,
        "views": 8100
    },
    {
        "title": "Reflective Nylon Dog Collar and Leash",
        "price": 899,
        "stock": 190,
        "brand": "Heads Up For Tails",
        "color": "Orange",
        "category": "pet-supplies",
        "sub_category": "accessories",
        "image": "https://picsum.photos/seed/dog-collar/600/600",
        "description": "Padded neoprene lining with high-visibility reflective stitching.",
        "discount": 74,
        "rating": 4.1,
        "sales": 540,
        "views": 7400
    }
]
